
title = "Shuttle - Gitleaks Config"

[extend]
useDefault = true

# Custom rules
[[rules]]
id = "azure-subscription-id"
description = "Azure Subscription ID"
regex = '''[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}'''
keywords = ["subscription"]
entropy = 3.0

[[rules]]
id = "azure-storage-key"
description = "Azure Storage Account Key"
regex = '''(?i)(DefaultEndpointsProtocol|AccountKey|SharedAccessSignature)'''
keywords = ["storage", "account", "key"]