<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="BinarySerializer" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Shuttle.BinarySerde.Common\Shuttle.BinarySerde.Common.csproj" />
    <ProjectReference Include="..\Shuttle.Fhm.Serde\Shuttle.Fhm.Serde.csproj" />
  </ItemGroup>
</Project>
