using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Shuttle.Models.Scouting;

namespace Shuttle.EFCore.Entities.Scouting;

/// <summary>
/// A user-created scouting team. Not tied to a real SHL/SMJHL franchise; it is simply a group that
/// owns one or more draft boards and has a set of members with roles. Created by a
/// <see cref="ShuttleUser"/>, who becomes its first <see cref="ScoutingTeamRole.Owner"/>.
/// </summary>
[EntityTypeConfiguration(typeof(ScoutingTeamEntityConfiguration))]
public class ScoutingTeam {
    /// <summary>The team's primary key. Generated by the application (non-enumerable).</summary>
    [DatabaseGenerated(DatabaseGeneratedOption.None)]
    public required Guid Id { get; set; }

    /// <summary>The team's display name.</summary>
    [MaxLength(ScoutingLimits.TeamNameMaxLength)]
    public required string Name { get; set; }

    /// <summary>The <see cref="ShuttleUser"/> who created the team.</summary>
    public required Guid CreatedByUserId { get; set; }

    /// <summary>When the team was created.</summary>
    public required DateTimeOffset CreatedAt { get; set; }

    /// <summary>When the team was last modified (name change, membership/board changes are tracked separately).</summary>
    public required DateTimeOffset UpdatedAt { get; set; }

    /// <summary>
    /// Optimistic-concurrency token. Every membership and board mutation touches the owning team row,
    /// so this serialises ownership-invariant changes: concurrent leave/remove/demote/delete requests
    /// that would race on the "team must keep an owner" rule collide here and one is rejected.
    /// </summary>
    [Timestamp]
    public byte[]? RowVersion { get; set; }

    public ShuttleUser CreatedBy { get; set; } = null!;

    public ICollection<ScoutingTeamMember> Members { get; set; } = new List<ScoutingTeamMember>();

    public ICollection<ScoutingBoard> Boards { get; set; } = new List<ScoutingBoard>();
}

public class ScoutingTeamEntityConfiguration : IEntityTypeConfiguration<ScoutingTeam> {
    public void Configure(EntityTypeBuilder<ScoutingTeam> builder) {
        builder.HasKey(t => t.Id);
        builder.Property(t => t.Id).ValueGeneratedNever();
        builder.Property(t => t.Name).HasMaxLength(ScoutingLimits.TeamNameMaxLength);
        builder.HasOne(t => t.CreatedBy)
            .WithMany()
            .HasForeignKey(t => t.CreatedByUserId)
            .OnDelete(DeleteBehavior.Restrict);
        builder.HasMany(t => t.Members)
            .WithOne(m => m.Team)
            .HasForeignKey(m => m.ScoutingTeamId)
            .OnDelete(DeleteBehavior.Cascade);
        builder.HasMany(t => t.Boards)
            .WithOne(b => b.Team)
            .HasForeignKey(b => b.ScoutingTeamId)
            .OnDelete(DeleteBehavior.Cascade);
    }
}
