-- drop indexes if they exist and rebuild if current ones
DROP INDEX IF EXISTS [IDX_QRTZ_T_J] ON [qrtz].[QRTZ_TRIGGERS];
DROP INDEX IF EXISTS [IDX_QRTZ_T_JG] ON [qrtz].[QRTZ_TRIGGERS];
DROP INDEX IF EXISTS [IDX_QRTZ_T_C] ON [qrtz].[QRTZ_TRIGGERS];
DROP INDEX IF EXISTS [IDX_QRTZ_T_G] ON [qrtz].[QRTZ_TRIGGERS];
DROP INDEX IF EXISTS [IDX_QRTZ_T_G_J] ON [qrtz].[QRTZ_TRIGGERS];
DROP INDEX IF EXISTS [IDX_QRTZ_T_STATE] ON [qrtz].[QRTZ_TRIGGERS];
DROP INDEX IF EXISTS [IDX_QRTZ_T_N_STATE] ON [qrtz].[QRTZ_TRIGGERS];
DROP INDEX IF EXISTS [IDX_QRTZ_T_N_G_STATE] ON [qrtz].[QRTZ_TRIGGERS];
DROP INDEX IF EXISTS [IDX_QRTZ_T_NEXT_FIRE_TIME] ON [qrtz].[QRTZ_TRIGGERS];
DROP INDEX IF EXISTS [IDX_QRTZ_T_NFT_ST] ON [qrtz].[QRTZ_TRIGGERS];
DROP INDEX IF EXISTS [IDX_QRTZ_T_NFT_MISFIRE] ON [qrtz].[QRTZ_TRIGGERS];
DROP INDEX IF EXISTS [IDX_QRTZ_T_NFT_ST_MISFIRE] ON [qrtz].[QRTZ_TRIGGERS];
DROP INDEX IF EXISTS [IDX_QRTZ_T_NFT_ST_MISFIRE_GRP] ON [qrtz].[QRTZ_TRIGGERS];
DROP INDEX IF EXISTS [IDX_QRTZ_FT_TRIG_INST_NAME] ON [qrtz].[QRTZ_FIRED_TRIGGERS];
DROP INDEX IF EXISTS [IDX_QRTZ_FT_INST_JOB_REQ_RCVRY] ON [qrtz].[QRTZ_FIRED_TRIGGERS];
DROP INDEX IF EXISTS [IDX_QRTZ_FT_J_G] ON [qrtz].[QRTZ_FIRED_TRIGGERS];
DROP INDEX IF EXISTS [IDX_QRTZ_FT_JG] ON [qrtz].[QRTZ_FIRED_TRIGGERS];
DROP INDEX IF EXISTS [IDX_QRTZ_FT_T_G] ON [qrtz].[QRTZ_FIRED_TRIGGERS];
DROP INDEX IF EXISTS [IDX_QRTZ_FT_TG] ON [qrtz].[QRTZ_FIRED_TRIGGERS];
DROP INDEX IF EXISTS [IDX_QRTZ_FT_G_J] ON [qrtz].[QRTZ_FIRED_TRIGGERS];
DROP INDEX IF EXISTS [IDX_QRTZ_FT_G_T] ON [qrtz].[QRTZ_FIRED_TRIGGERS];

IF OBJECT_ID(N'[qrtz].[FK_QRTZ_TRIGGERS_QRTZ_JOB_DETAILS]', N'F') IS NOT NULL
ALTER TABLE [qrtz].[QRTZ_TRIGGERS] DROP CONSTRAINT [FK_QRTZ_TRIGGERS_QRTZ_JOB_DETAILS];

IF OBJECT_ID(N'[qrtz].[FK_QRTZ_CRON_TRIGGERS_QRTZ_TRIGGERS]', N'F') IS NOT NULL
ALTER TABLE [qrtz].[QRTZ_CRON_TRIGGERS] DROP CONSTRAINT [FK_QRTZ_CRON_TRIGGERS_QRTZ_TRIGGERS];

IF OBJECT_ID(N'[qrtz].[FK_QRTZ_SIMPLE_TRIGGERS_QRTZ_TRIGGERS]', N'F') IS NOT NULL
ALTER TABLE [qrtz].[QRTZ_SIMPLE_TRIGGERS] DROP CONSTRAINT [FK_QRTZ_SIMPLE_TRIGGERS_QRTZ_TRIGGERS];

IF OBJECT_ID(N'[qrtz].[FK_QRTZ_SIMPROP_TRIGGERS_QRTZ_TRIGGERS]', N'F') IS NOT NULL
ALTER TABLE [qrtz].[QRTZ_SIMPROP_TRIGGERS] DROP CONSTRAINT [FK_QRTZ_SIMPROP_TRIGGERS_QRTZ_TRIGGERS];

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[qrtz].[FK_QRTZ_JOB_LISTENERS_QRTZ_JOB_DETAILS]') AND parent_object_id = OBJECT_ID(N'[qrtz].[QRTZ_JOB_LISTENERS]'))
ALTER TABLE [qrtz].[QRTZ_JOB_LISTENERS] DROP CONSTRAINT [FK_QRTZ_JOB_LISTENERS_QRTZ_JOB_DETAILS];

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[qrtz].[FK_QRTZ_TRIGGER_LISTENERS_QRTZ_TRIGGERS]') AND parent_object_id = OBJECT_ID(N'[qrtz].[QRTZ_TRIGGER_LISTENERS]'))
ALTER TABLE [qrtz].[QRTZ_TRIGGER_LISTENERS] DROP CONSTRAINT [FK_QRTZ_TRIGGER_LISTENERS_QRTZ_TRIGGERS];

IF OBJECT_ID(N'[qrtz].[QRTZ_CALENDARS]', N'U') IS NOT NULL
    DROP TABLE [qrtz].[QRTZ_CALENDARS];

IF OBJECT_ID(N'[qrtz].[QRTZ_CRON_TRIGGERS]', N'U') IS NOT NULL
    DROP TABLE [qrtz].[QRTZ_CRON_TRIGGERS];

IF OBJECT_ID(N'[qrtz].[QRTZ_BLOB_TRIGGERS]', N'U') IS NOT NULL
    DROP TABLE [qrtz].[QRTZ_BLOB_TRIGGERS];

IF OBJECT_ID(N'[qrtz].[QRTZ_FIRED_TRIGGERS]', N'U') IS NOT NULL
    DROP TABLE [qrtz].[QRTZ_FIRED_TRIGGERS];

IF OBJECT_ID(N'[qrtz].[QRTZ_PAUSED_TRIGGER_GRPS]', N'U') IS NOT NULL
    DROP TABLE [qrtz].[QRTZ_PAUSED_TRIGGER_GRPS];

IF  OBJECT_ID(N'[qrtz].[QRTZ_JOB_LISTENERS]', N'U') IS NOT NULL
    DROP TABLE [qrtz].[QRTZ_JOB_LISTENERS];

IF OBJECT_ID(N'[qrtz].[QRTZ_SCHEDULER_STATE]', N'U') IS NOT NULL
    DROP TABLE [qrtz].[QRTZ_SCHEDULER_STATE];

IF OBJECT_ID(N'[qrtz].[QRTZ_LOCKS]', N'U') IS NOT NULL
    DROP TABLE [qrtz].[QRTZ_LOCKS];

IF OBJECT_ID(N'[qrtz].[QRTZ_TRIGGER_LISTENERS]', N'U') IS NOT NULL
    DROP TABLE [qrtz].[QRTZ_TRIGGER_LISTENERS];

IF OBJECT_ID(N'[qrtz].[QRTZ_JOB_DETAILS]', N'U') IS NOT NULL
    DROP TABLE [qrtz].[QRTZ_JOB_DETAILS];

IF OBJECT_ID(N'[qrtz].[QRTZ_SIMPLE_TRIGGERS]', N'U') IS NOT NULL
    DROP TABLE [qrtz].[QRTZ_SIMPLE_TRIGGERS];

IF OBJECT_ID(N'[qrtz].[QRTZ_SIMPROP_TRIGGERS]', N'U') IS NOT NULL
    DROP TABLE [qrtz].[QRTZ_SIMPROP_TRIGGERS];

IF OBJECT_ID(N'[qrtz].[QRTZ_TRIGGERS]', N'U') IS NOT NULL
    DROP TABLE [qrtz].[QRTZ_TRIGGERS];