// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shuttle.EFCore;

#nullable disable

namespace Shuttle.EFCore.Migrations
{
    [DbContext(typeof(ShlDbContext))]
    [Migration("20260721211145_AddScoutingProspectStatusAndAssignment")]
    partial class AddScoutingProspectStatusAndAssignment
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Shuttle.EFCore.Entities.Index.Conference", b =>
                {
                    b.Property<int>("ConferenceId")
                        .HasColumnType("int");

                    b.Property<int>("LeagueId")
                        .HasColumnType("int");

                    b.Property<int>("Season")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("ConferenceId", "LeagueId", "Season");

                    b.HasIndex("Name");

                    b.HasIndex("Season");

                    b.HasIndex("LeagueId", "Season");

                    b.ToTable("Conferences");
                });

            modelBuilder.Entity("Shuttle.EFCore.Entities.Index.Division", b =>
                {
                    b.Property<int>("DivisionId")
                        .HasColumnType("int");

                    b.Property<int>("Season")
                        .HasColumnType("int");

                    b.Property<int>("LeagueId")
                        .HasColumnType("int");

                    b.Property<int>("ConferenceId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DivisionId", "Season", "LeagueId", "ConferenceId");

                    b.HasIndex("ConferenceId", "LeagueId", "Season");

                    b.ToTable("Divisions");
                });

            modelBuilder.Entity("Shuttle.EFCore.Entities.Index.GameResult", b =>
                {
                    b.Property<string>("Slug")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("AwayScore")
                        .HasColumnType("int");

                    b.Property<int>("AwayTeamId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("DatePlayed")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("GameId")
                        .HasColumnType("int");

                    b.Property<int>("GameType")
                        .HasColumnType("int");

                    b.Property<int>("HomeScore")
                        .HasColumnType("int");

                    b.Property<int>("HomeTeamId")
                        .HasColumnType("int");

                    b.Property<int>("LeagueId")
                        .HasColumnType("int");

                    b.Property<bool>("Overtime")
                        .HasColumnType("bit");

                    b.Property<bool>("Played")
                        .HasColumnType("bit");

                    b.Property<int>("Season")
                        .HasColumnType("int");

                    b.Property<bool>("Shootout")
                        .HasColumnType("bit");

                    b.Property<DateOnly>("SimDate")
                        .HasColumnType("date");

                    b.HasKey("Slug");

                    b.HasIndex("LeagueId", "GameId")
                        .IsUnique()
                        .HasFilter("GameId IS NOT NULL");

                    b.HasIndex("LeagueId", "Season");

                    b.HasIndex("LeagueId", "SimDate");

                    b.HasIndex("AwayTeamId", "Season", "LeagueId");

                    b.HasIndex("HomeTeamId", "Season", "LeagueId");

                    b.ToTable("GameResults");
                });

            modelBuilder.Entity("Shuttle.EFCore.Entities.Index.League", b =>
                {
                    b.Property<int>("LeagueId")
                        .HasColumnType("int");

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("LeagueId");

                    b.HasIndex("Abbreviation")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Leagues");
                });

            modelBuilder.Entity("Shuttle.EFCore.Entities.Index.LeagueSeason", b =>
                {
                    b.Property<int>("LeagueId")
                        .HasColumnType("int");

                    b.Property<int>("Season")
                        .HasColumnType("int");

                    b.HasKey("LeagueId", "Season");

                    b.HasIndex("Season");

                    b.ToTable("Seasons");
                });

            modelBuilder.Entity("Shuttle.EFCore.Entities.Performance.MostRecentUserPlayer", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.HasIndex("PlayerId")
                        .IsUnique();

                    b.ToTable("MostRecentUserPlayers");
                });

            modelBuilder.Entity("Shuttle.EFCore.Entities.Portal.IndexRecord", b =>
                {
                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("LeagueId")
                        .HasColumnType("int");

                    b.Property<int>("StartSeason")
                        .HasColumnType("int");

                    b.Property<int>("IndexId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ValidFrom")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("ValidFrom");

                    b.Property<DateTime>("ValidTo")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("ValidTo");

                    b.HasKey("PlayerId", "LeagueId", "StartSeason");

                    b.HasIndex("IndexId");

                    b.HasIndex("UserId");

                    b.HasIndex("PlayerId", "UserId");

                    b.ToTable("IndexRecords");

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("IndexRecordsHistory");
                                ttb
                                    .HasPeriodStart("ValidFrom")
                                    .HasColumnName("ValidFrom");
                                ttb
                                    .HasPeriodEnd("ValidTo")
                                    .HasColumnName("ValidTo");
                            }));
                });

            modelBuilder.Entity("Shuttle.EFCore.Entities.Portal.PlayerInformation", b =>
                {
                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<bool>("ActivityCheckComplete")
                        .HasColumnType("bit");

                    b.Property<int>("AppliedTpe")
                        .HasColumnType("int");

                    b.Property<int>("BankBalance")
                        .HasColumnType("int");

                    b.Property<int>("BankedTpe")
                        .HasColumnType("int");

                    b.Property<string>("Birthplace")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("CoachingPurchased")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CurrentLeague")
                        .HasColumnType("int");

                    b.Property<int?>("CurrentTeamId")
                        .HasColumnType("int");

                    b.Property<int?>("DraftSeason")
                        .HasColumnType("int");

                    b.Property<int>("Handedness")
                        .HasColumnType("int");

                    b.Property<string>("IihfNation")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<bool>("Inactive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSuspended")
                        .HasColumnType("bit");

                    b.Property<int?>("JerseyNumber")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<bool>("PositionChanged")
                        .HasColumnType("bit");

                    b.Property<string>("Recruiter")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Render")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTime?>("RetirementDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ShlRightsTeamId")
                        .HasColumnType("int");

                    b.Property<int?>("SmjhlRightsTeamId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("TaskStatus")
                        .HasColumnType("int");

                    b.Property<int>("TotalTpe")
                        .HasColumnType("int");

                    b.Property<bool>("TrainingCampComplete")
                        .HasColumnType("bit");

                    b.Property<int>("TrainingPurchased")
                        .HasColumnType("int");

                    b.Property<int>("UsedRedistribution")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTime>("ValidFrom")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("ValidFrom");

                    b.Property<DateTime>("ValidTo")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("ValidTo");

                    b.Property<int?>("Weight")
                        .HasColumnType("int");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "GoaltenderAttributes", "Shuttle.EFCore.Entities.Portal.PlayerInformation.GoaltenderAttributes#GoaltenderAttributes", b1 =>
                        {
                            b1.Property<int>("Aggression")
                                .HasColumnType("int");

                            b1.Property<int>("Blocker")
                                .HasColumnType("int");

                            b1.Property<int>("Determination")
                                .HasColumnType("int");

                            b1.Property<int>("Glove")
                                .HasColumnType("int");

                            b1.Property<int>("Leadership")
                                .HasColumnType("int");

                            b1.Property<int>("LowShots")
                                .HasColumnType("int");

                            b1.Property<int>("MentalToughness")
                                .HasColumnType("int");

                            b1.Property<int>("Passing")
                                .HasColumnType("int");

                            b1.Property<int>("PokeCheck")
                                .HasColumnType("int");

                            b1.Property<int>("Positioning")
                                .HasColumnType("int");

                            b1.Property<int>("Professionalism")
                                .HasColumnType("int");

                            b1.Property<int>("Puckhandling")
                                .HasColumnType("int");

                            b1.Property<int>("Rebound")
                                .HasColumnType("int");

                            b1.Property<int>("Recovery")
                                .HasColumnType("int");

                            b1.Property<int>("Reflexes")
                                .HasColumnType("int");

                            b1.Property<int>("Skating")
                                .HasColumnType("int");

                            b1.Property<int>("Stamina")
                                .HasColumnType("int")
                                .HasJsonPropertyName("goaltenderStamina");

                            b1.Property<int>("TeamPlayer")
                                .HasColumnType("int");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Height", "Shuttle.EFCore.Entities.Portal.PlayerInformation.Height#Height", b1 =>
                        {
                            b1.Property<int>("Feet");

                            b1.Property<int>("Inches");

                            b1
                                .ToJson("Height")
                                .HasColumnType("json");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "SkaterAttributes", "Shuttle.EFCore.Entities.Portal.PlayerInformation.SkaterAttributes#SkaterAttributes", b1 =>
                        {
                            b1.Property<int>("Acceleration")
                                .HasColumnType("int");

                            b1.Property<int>("Aggression")
                                .HasColumnType("int");

                            b1.Property<int>("Agility")
                                .HasColumnType("int");

                            b1.Property<int>("Balance")
                                .HasColumnType("int");

                            b1.Property<int>("Bravery")
                                .HasColumnType("int");

                            b1.Property<int>("Checking")
                                .HasColumnType("int");

                            b1.Property<int>("DefensiveRead")
                                .HasColumnType("int");

                            b1.Property<int>("Determination")
                                .HasColumnType("int");

                            b1.Property<int>("Faceoffs")
                                .HasColumnType("int");

                            b1.Property<int>("Fighting")
                                .HasColumnType("int");

                            b1.Property<int>("GettingOpen")
                                .HasColumnType("int");

                            b1.Property<int>("Hitting")
                                .HasColumnType("int");

                            b1.Property<int>("Leadership")
                                .HasColumnType("int");

                            b1.Property<int>("OffensiveRead")
                                .HasColumnType("int");

                            b1.Property<int>("Passing")
                                .HasColumnType("int");

                            b1.Property<int>("Positioning")
                                .HasColumnType("int");

                            b1.Property<int>("Professionalism")
                                .HasColumnType("int");

                            b1.Property<int>("Puckhandling")
                                .HasColumnType("int");

                            b1.Property<int>("Screening")
                                .HasColumnType("int");

                            b1.Property<int>("ShootingAccuracy")
                                .HasColumnType("int");

                            b1.Property<int>("ShootingRange")
                                .HasColumnType("int");

                            b1.Property<int>("ShotBlocking")
                                .HasColumnType("int");

                            b1.Property<int>("Speed")
                                .HasColumnType("int");

                            b1.Property<int>("Stamina")
                                .HasColumnType("int");

                            b1.Property<int>("Stickchecking")
                                .HasColumnType("int");

                            b1.Property<int>("Strength")
                                .HasColumnType("int");

                            b1.Property<int>("TeamPlayer")
                                .HasColumnType("int");

                            b1.Property<int>("Temperament")
                                .HasColumnType("int");
                        });

                    b.HasKey("PlayerId");

                    b.HasAlternateKey("UserId", "PlayerId");

                    b.HasIndex("CurrentTeamId");

                    b.HasIndex("DraftSeason");

                    b.HasIndex("Name");

                    b.HasIndex("Username");

                    b.HasIndex("UserId", "CreationTime", "PlayerId");

                    b.ToTable("PlayerInformation");

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("PlayerInformationHistory");
                                ttb
                                    .HasPeriodStart("ValidFrom")
                                    .HasColumnName("ValidFrom");
                                ttb
                                    .HasPeriodEnd("ValidTo")
                                    .HasColumnName("ValidTo");
                            }));
                });

            modelBuilder.Entity("Shuttle.EFCore.Entities.Portal.TpeEvent", b =>
                {
                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TaskDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TotalTpe")
                        .HasColumnType("int");

                    b.HasKey("PlayerId", "TaskDate");

                    b.ToTable("TpeEvents");
                });

            modelBuilder.Entity("Shuttle.EFCore.Entities.Scouting.ScoutingBoard", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("DraftSeason")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("ScoutingTeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("ScoutingTeamId");

                    b.ToTable("ScoutingBoards");
                });

            modelBuilder.Entity("Shuttle.EFCore.Entities.Scouting.ScoutingBoardEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("AssignedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("AssignedToUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("Rank")
                        .HasColumnType("int");

                    b.Property<Guid>("ScoutingBoardId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("AssignedToUserId");

                    b.HasIndex("ScoutingBoardId", "PlayerId")
                        .IsUnique();

                    b.HasIndex("ScoutingBoardId", "Rank");

                    b.HasIndex("ScoutingBoardId", "Status");

                    b.ToTable("ScoutingBoardEntries");
                });

            modelBuilder.Entity("Shuttle.EFCore.Entities.Scouting.ScoutingComment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AuthorUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("EditedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("ScoutingBoardEntryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ScoutingBoardId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AuthorUserId");

                    b.HasIndex("ScoutingBoardEntryId");

                    b.HasIndex("ScoutingBoardId", "ScoutingBoardEntryId", "CreatedAt");

                    b.ToTable("ScoutingComments");
                });

            modelBuilder.Entity("Shuttle.EFCore.Entities.Scouting.ScoutingTeam", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("ScoutingTeams");
                });

            modelBuilder.Entity("Shuttle.EFCore.Entities.Scouting.ScoutingTeamMember", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<Guid>("ScoutingTeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ShuttleUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ShuttleUserId");

                    b.HasIndex("ScoutingTeamId", "ShuttleUserId")
                        .IsUnique();

                    b.ToTable("ScoutingTeamMembers");
                });

            modelBuilder.Entity("Shuttle.EFCore.Entities.ShlUser", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("DiscordId")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("UserId");

                    b.HasIndex("Name");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Shuttle.EFCore.Entities.ShuttleUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ObjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("ObjectId")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("ShuttleUsers");
                });

            modelBuilder.Entity("Shuttle.EFCore.Entities.Team", b =>
                {
                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.Property<int>("Season")
                        .HasColumnType("int");

                    b.Property<int>("LeagueId")
                        .HasColumnType("int");

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<int>("ConferenceId")
                        .HasColumnType("int");

                    b.Property<int?>("DivisionId")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Colors", "Shuttle.EFCore.Entities.Team.Colors#TeamColors", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Primary")
                                .IsRequired();

                            b1.Property<string>("Secondary")
                                .IsRequired();

                            b1.Property<string>("Text");

                            b1
                                .ToJson("Colors")
                                .HasColumnType("json");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "NameDetails", "Shuttle.EFCore.Entities.Team.NameDetails#NameDetails", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("First")
                                .IsRequired();

                            b1.Property<string>("Second")
                                .IsRequired();

                            b1
                                .ToJson("NameDetails")
                                .HasColumnType("json");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Stats", "Shuttle.EFCore.Entities.Team.Stats#TeamSeasonStats", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("GoalsAgainst")
                                .HasColumnType("int");

                            b1.Property<int>("GoalsFor")
                                .HasColumnType("int");

                            b1.Property<int>("Losses")
                                .HasColumnType("int");

                            b1.Property<int>("OvertimeLosses")
                                .HasColumnType("int");

                            b1.Property<int>("Points")
                                .HasColumnType("int");

                            b1.Property<int>("ShootoutLosses")
                                .HasColumnType("int");

                            b1.Property<int>("ShootoutWins")
                                .HasColumnType("int");

                            b1.Property<float>("WinPercent")
                                .HasColumnType("real");

                            b1.Property<int>("Wins")
                                .HasColumnType("int");
                        });

                    b.HasKey("TeamId", "Season", "LeagueId");

                    b.HasAlternateKey("Season", "LeagueId", "Abbreviation");

                    b.HasIndex("Location");

                    b.HasIndex("Name");

                    b.HasIndex("ConferenceId", "Season", "LeagueId");

                    b.HasIndex("ConferenceId", "DivisionId", "Season", "LeagueId");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("Shuttle.EFCore.Entities.Index.Conference", b =>
                {
                    b.HasOne("Shuttle.EFCore.Entities.Index.LeagueSeason", "LeagueSeason")
                        .WithMany()
                        .HasForeignKey("LeagueId", "Season")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LeagueSeason");
                });

            modelBuilder.Entity("Shuttle.EFCore.Entities.Index.Division", b =>
                {
                    b.HasOne("Shuttle.EFCore.Entities.Index.Conference", "Conference")
                        .WithMany()
                        .HasForeignKey("ConferenceId", "LeagueId", "Season")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conference");
                });

            modelBuilder.Entity("Shuttle.EFCore.Entities.Index.GameResult", b =>
                {
                    b.HasOne("Shuttle.EFCore.Entities.Index.LeagueSeason", "LeagueSeason")
                        .WithMany()
                        .HasForeignKey("LeagueId", "Season")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shuttle.EFCore.Entities.Team", "AwayTeam")
                        .WithMany()
                        .HasForeignKey("AwayTeamId", "Season", "LeagueId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("Shuttle.EFCore.Entities.Team", "HomeTeam")
                        .WithMany()
                        .HasForeignKey("HomeTeamId", "Season", "LeagueId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("AwayTeam");

                    b.Navigation("HomeTeam");

                    b.Navigation("LeagueSeason");
                });

            modelBuilder.Entity("Shuttle.EFCore.Entities.Index.LeagueSeason", b =>
                {
                    b.HasOne("Shuttle.EFCore.Entities.Index.League", "League")
                        .WithMany()
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("League");
                });

            modelBuilder.Entity("Shuttle.EFCore.Entities.Performance.MostRecentUserPlayer", b =>
                {
                    b.HasOne("Shuttle.EFCore.Entities.Portal.PlayerInformation", "Player")
                        .WithOne()
                        .HasForeignKey("Shuttle.EFCore.Entities.Performance.MostRecentUserPlayer", "PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Shuttle.EFCore.Entities.Portal.IndexRecord", b =>
                {
                    b.HasOne("Shuttle.EFCore.Entities.Portal.PlayerInformation", "Player")
                        .WithMany("IndexRecords")
                        .HasForeignKey("PlayerId", "UserId")
                        .HasPrincipalKey("PlayerId", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Shuttle.EFCore.Entities.Portal.PlayerInformation", b =>
                {
                    b.HasOne("Shuttle.EFCore.Entities.ShlUser", "User")
                        .WithMany("Players")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Shuttle.EFCore.Entities.Portal.TpeEvent", b =>
                {
                    b.HasOne("Shuttle.EFCore.Entities.Portal.PlayerInformation", "Player")
                        .WithMany("TpeEvents")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Shuttle.EFCore.Entities.Scouting.ScoutingBoard", b =>
                {
                    b.HasOne("Shuttle.EFCore.Entities.Scouting.ScoutingTeam", "Team")
                        .WithMany("Boards")
                        .HasForeignKey("ScoutingTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Shuttle.EFCore.Entities.Scouting.ScoutingBoardEntry", b =>
                {
                    b.HasOne("Shuttle.EFCore.Entities.ShuttleUser", "AssignedTo")
                        .WithMany()
                        .HasForeignKey("AssignedToUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Shuttle.EFCore.Entities.Scouting.ScoutingBoard", "Board")
                        .WithMany("Entries")
                        .HasForeignKey("ScoutingBoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedTo");

                    b.Navigation("Board");
                });

            modelBuilder.Entity("Shuttle.EFCore.Entities.Scouting.ScoutingComment", b =>
                {
                    b.HasOne("Shuttle.EFCore.Entities.ShuttleUser", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Shuttle.EFCore.Entities.Scouting.ScoutingBoardEntry", "Entry")
                        .WithMany("Comments")
                        .HasForeignKey("ScoutingBoardEntryId")
                        .OnDelete(DeleteBehavior.ClientCascade);

                    b.HasOne("Shuttle.EFCore.Entities.Scouting.ScoutingBoard", "Board")
                        .WithMany("Comments")
                        .HasForeignKey("ScoutingBoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Board");

                    b.Navigation("Entry");
                });

            modelBuilder.Entity("Shuttle.EFCore.Entities.Scouting.ScoutingTeam", b =>
                {
                    b.HasOne("Shuttle.EFCore.Entities.ShuttleUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("Shuttle.EFCore.Entities.Scouting.ScoutingTeamMember", b =>
                {
                    b.HasOne("Shuttle.EFCore.Entities.Scouting.ScoutingTeam", "Team")
                        .WithMany("Members")
                        .HasForeignKey("ScoutingTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shuttle.EFCore.Entities.ShuttleUser", "User")
                        .WithMany()
                        .HasForeignKey("ShuttleUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Team");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Shuttle.EFCore.Entities.Team", b =>
                {
                    b.HasOne("Shuttle.EFCore.Entities.Index.Conference", "Conference")
                        .WithMany()
                        .HasForeignKey("ConferenceId", "Season", "LeagueId")
                        .HasPrincipalKey("ConferenceId", "Season", "LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shuttle.EFCore.Entities.Index.Division", "Division")
                        .WithMany()
                        .HasForeignKey("ConferenceId", "DivisionId", "Season", "LeagueId")
                        .HasPrincipalKey("ConferenceId", "DivisionId", "Season", "LeagueId")
                        .OnDelete(DeleteBehavior.ClientCascade);

                    b.Navigation("Conference");

                    b.Navigation("Division");
                });

            modelBuilder.Entity("Shuttle.EFCore.Entities.Portal.PlayerInformation", b =>
                {
                    b.Navigation("IndexRecords");

                    b.Navigation("TpeEvents");
                });

            modelBuilder.Entity("Shuttle.EFCore.Entities.Scouting.ScoutingBoard", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Entries");
                });

            modelBuilder.Entity("Shuttle.EFCore.Entities.Scouting.ScoutingBoardEntry", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("Shuttle.EFCore.Entities.Scouting.ScoutingTeam", b =>
                {
                    b.Navigation("Boards");

                    b.Navigation("Members");
                });

            modelBuilder.Entity("Shuttle.EFCore.Entities.ShlUser", b =>
                {
                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
