// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shuttle.EFCore;

#nullable disable

namespace Shuttle.EFCore.Migrations
{
    [DbContext(typeof(ShlDbContext))]
    [Migration("20260709023001_InitialSqlite")]
    partial class InitialSqlite
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("Shuttle.EFCore.Entities.Index.Conference", b =>
                {
                    b.Property<int>("ConferenceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LeagueId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Season")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("ConferenceId", "LeagueId", "Season");

                    b.HasIndex("Name");

                    b.HasIndex("Season");

                    b.HasIndex("LeagueId", "Season");

                    b.ToTable("Conferences");
                });

            modelBuilder.Entity("Shuttle.EFCore.Entities.Index.Division", b =>
                {
                    b.Property<int>("DivisionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Season")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LeagueId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConferenceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("DivisionId", "Season", "LeagueId", "ConferenceId");

                    b.HasIndex("ConferenceId", "LeagueId", "Season");

                    b.ToTable("Divisions");
                });

            modelBuilder.Entity("Shuttle.EFCore.Entities.Index.GameResult", b =>
                {
                    b.Property<string>("Slug")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("AwayScore")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AwayTeamId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("DatePlayed")
                        .HasColumnType("TEXT");

                    b.Property<int?>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HomeScore")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HomeTeamId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LeagueId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Overtime")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Played")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Season")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Shootout")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("SimDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Slug");

                    b.HasIndex("LeagueId", "GameId")
                        .IsUnique()
                        .HasFilter("GameId IS NOT NULL");

                    b.HasIndex("LeagueId", "Season");

                    b.HasIndex("LeagueId", "SimDate");

                    b.HasIndex("AwayTeamId", "Season", "LeagueId");

                    b.HasIndex("HomeTeamId", "Season", "LeagueId");

                    b.ToTable("GameResults");
                });

            modelBuilder.Entity("Shuttle.EFCore.Entities.Index.League", b =>
                {
                    b.Property<int>("LeagueId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("LeagueId");

                    b.HasIndex("Abbreviation")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Leagues");
                });

            modelBuilder.Entity("Shuttle.EFCore.Entities.Index.LeagueSeason", b =>
                {
                    b.Property<int>("LeagueId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Season")
                        .HasColumnType("INTEGER");

                    b.HasKey("LeagueId", "Season");

                    b.HasIndex("Season");

                    b.ToTable("Seasons");
                });

            modelBuilder.Entity("Shuttle.EFCore.Entities.Performance.MostRecentUserPlayer", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId");

                    b.HasIndex("PlayerId")
                        .IsUnique();

                    b.ToTable("MostRecentUserPlayers");
                });

            modelBuilder.Entity("Shuttle.EFCore.Entities.Portal.IndexRecord", b =>
                {
                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LeagueId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StartSeason")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IndexId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ValidFrom")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("ValidTo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("'9999-12-31 23:59:59'");

                    b.HasKey("PlayerId", "LeagueId", "StartSeason");

                    b.HasIndex("IndexId");

                    b.HasIndex("UserId");

                    b.HasIndex("PlayerId", "UserId");

                    b.ToTable("IndexRecords");

                    b.HasAnnotation("Shuttle:Temporal", true);
                });

            modelBuilder.Entity("Shuttle.EFCore.Entities.Portal.PlayerInformation", b =>
                {
                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ActivityCheckComplete")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AppliedTpe")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BankBalance")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BankedTpe")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Birthplace")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<int>("CoachingPurchased")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CurrentLeague")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CurrentTeamId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DraftSeason")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Handedness")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IihfNation")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Inactive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSuspended")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("JerseyNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PositionChanged")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Recruiter")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("Render")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RetirementDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ShlRightsTeamId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SmjhlRightsTeamId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TaskStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalTpe")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("TrainingCampComplete")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TrainingPurchased")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsedRedistribution")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ValidFrom")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("ValidTo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("'9999-12-31 23:59:59'");

                    b.Property<int?>("Weight")
                        .HasColumnType("INTEGER");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "GoaltenderAttributes", "Shuttle.EFCore.Entities.Portal.PlayerInformation.GoaltenderAttributes#GoaltenderAttributes", b1 =>
                        {
                            b1.Property<int>("Aggression")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Blocker")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Determination")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Glove")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Leadership")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("LowShots")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("MentalToughness")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Passing")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("PokeCheck")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Positioning")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Professionalism")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Puckhandling")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Rebound")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Recovery")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Reflexes")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Skating")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Stamina")
                                .HasColumnType("INTEGER")
                                .HasJsonPropertyName("goaltenderStamina");

                            b1.Property<int>("TeamPlayer")
                                .HasColumnType("INTEGER");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Height", "Shuttle.EFCore.Entities.Portal.PlayerInformation.Height#Height", b1 =>
                        {
                            b1.Property<int>("Feet");

                            b1.Property<int>("Inches");

                            b1
                                .ToJson("Height")
                                .HasColumnType("TEXT");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "SkaterAttributes", "Shuttle.EFCore.Entities.Portal.PlayerInformation.SkaterAttributes#SkaterAttributes", b1 =>
                        {
                            b1.Property<int>("Acceleration")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Aggression")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Agility")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Balance")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Bravery")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Checking")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("DefensiveRead")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Determination")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Faceoffs")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Fighting")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("GettingOpen")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Hitting")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Leadership")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("OffensiveRead")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Passing")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Positioning")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Professionalism")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Puckhandling")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Screening")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("ShootingAccuracy")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("ShootingRange")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("ShotBlocking")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Speed")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Stamina")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Stickchecking")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Strength")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("TeamPlayer")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Temperament")
                                .HasColumnType("INTEGER");
                        });

                    b.HasKey("PlayerId");

                    b.HasAlternateKey("UserId", "PlayerId");

                    b.HasIndex("CurrentTeamId");

                    b.HasIndex("DraftSeason");

                    b.HasIndex("Name");

                    b.HasIndex("Username");

                    b.HasIndex("UserId", "CreationTime", "PlayerId");

                    b.ToTable("PlayerInformation");

                    b.HasAnnotation("Shuttle:Temporal", true);
                });

            modelBuilder.Entity("Shuttle.EFCore.Entities.ShlUser", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DiscordId")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.HasIndex("Name");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Shuttle.EFCore.Entities.Team", b =>
                {
                    b.Property<int>("TeamId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Season")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LeagueId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<int>("ConferenceId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DivisionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Colors", "Shuttle.EFCore.Entities.Team.Colors#TeamColors", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Primary")
                                .IsRequired();

                            b1.Property<string>("Secondary")
                                .IsRequired();

                            b1.Property<string>("Text");

                            b1
                                .ToJson("Colors")
                                .HasColumnType("TEXT");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "NameDetails", "Shuttle.EFCore.Entities.Team.NameDetails#NameDetails", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("First")
                                .IsRequired();

                            b1.Property<string>("Second")
                                .IsRequired();

                            b1
                                .ToJson("NameDetails")
                                .HasColumnType("TEXT");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Stats", "Shuttle.EFCore.Entities.Team.Stats#TeamSeasonStats", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("GoalsAgainst")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("GoalsFor")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Losses")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("OvertimeLosses")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Points")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("ShootoutLosses")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("ShootoutWins")
                                .HasColumnType("INTEGER");

                            b1.Property<float>("WinPercent")
                                .HasColumnType("REAL");

                            b1.Property<int>("Wins")
                                .HasColumnType("INTEGER");
                        });

                    b.HasKey("TeamId", "Season", "LeagueId");

                    b.HasAlternateKey("Season", "LeagueId", "Abbreviation");

                    b.HasIndex("Location");

                    b.HasIndex("Name");

                    b.HasIndex("ConferenceId", "Season", "LeagueId");

                    b.HasIndex("DivisionId", "Season", "LeagueId");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("Shuttle.EFCore.Entities.Index.Conference", b =>
                {
                    b.HasOne("Shuttle.EFCore.Entities.Index.LeagueSeason", "LeagueSeason")
                        .WithMany()
                        .HasForeignKey("LeagueId", "Season")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LeagueSeason");
                });

            modelBuilder.Entity("Shuttle.EFCore.Entities.Index.Division", b =>
                {
                    b.HasOne("Shuttle.EFCore.Entities.Index.Conference", "Conference")
                        .WithMany()
                        .HasForeignKey("ConferenceId", "LeagueId", "Season")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conference");
                });

            modelBuilder.Entity("Shuttle.EFCore.Entities.Index.GameResult", b =>
                {
                    b.HasOne("Shuttle.EFCore.Entities.Index.LeagueSeason", "LeagueSeason")
                        .WithMany()
                        .HasForeignKey("LeagueId", "Season")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shuttle.EFCore.Entities.Team", "AwayTeam")
                        .WithMany()
                        .HasForeignKey("AwayTeamId", "Season", "LeagueId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("Shuttle.EFCore.Entities.Team", "HomeTeam")
                        .WithMany()
                        .HasForeignKey("HomeTeamId", "Season", "LeagueId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("AwayTeam");

                    b.Navigation("HomeTeam");

                    b.Navigation("LeagueSeason");
                });

            modelBuilder.Entity("Shuttle.EFCore.Entities.Index.LeagueSeason", b =>
                {
                    b.HasOne("Shuttle.EFCore.Entities.Index.League", "League")
                        .WithMany()
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("League");
                });

            modelBuilder.Entity("Shuttle.EFCore.Entities.Performance.MostRecentUserPlayer", b =>
                {
                    b.HasOne("Shuttle.EFCore.Entities.Portal.PlayerInformation", "Player")
                        .WithOne()
                        .HasForeignKey("Shuttle.EFCore.Entities.Performance.MostRecentUserPlayer", "PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Shuttle.EFCore.Entities.Portal.IndexRecord", b =>
                {
                    b.HasOne("Shuttle.EFCore.Entities.Portal.PlayerInformation", "Player")
                        .WithMany("IndexRecords")
                        .HasForeignKey("PlayerId", "UserId")
                        .HasPrincipalKey("PlayerId", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Shuttle.EFCore.Entities.Portal.PlayerInformation", b =>
                {
                    b.HasOne("Shuttle.EFCore.Entities.ShlUser", "User")
                        .WithMany("Players")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Shuttle.EFCore.Entities.Team", b =>
                {
                    b.HasOne("Shuttle.EFCore.Entities.Index.Conference", "Conference")
                        .WithMany()
                        .HasForeignKey("ConferenceId", "Season", "LeagueId")
                        .HasPrincipalKey("ConferenceId", "Season", "LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shuttle.EFCore.Entities.Index.Division", "Division")
                        .WithMany()
                        .HasForeignKey("DivisionId", "Season", "LeagueId")
                        .HasPrincipalKey("DivisionId", "Season", "LeagueId")
                        .OnDelete(DeleteBehavior.ClientCascade);

                    b.Navigation("Conference");

                    b.Navigation("Division");
                });

            modelBuilder.Entity("Shuttle.EFCore.Entities.Portal.PlayerInformation", b =>
                {
                    b.Navigation("IndexRecords");
                });

            modelBuilder.Entity("Shuttle.EFCore.Entities.ShlUser", b =>
                {
                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
