// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shuttle.Fhm.Serde.Sqlite;

#nullable disable

namespace Shuttle.Fhm.Serde.Sqlite.Migrations
{
    [DbContext(typeof(FhmSaveSqliteContext))]
    [Migration("20260901224012_PreserveRawPersonnelBirthDate")]
    partial class PreserveRawPersonnelBirthDate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("Shuttle.Fhm.Serde.Sqlite.Entities.GameSetting", b =>
                {
                    b.Property<int>("SettingOrdinal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SettingType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.HasKey("SettingOrdinal");

                    b.ToTable("GameSettings", (string)null);

                    b.HasDiscriminator<string>("SettingType").HasValue("GameSetting");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Shuttle.Fhm.Serde.Sqlite.Entities.ModifierCatalogue", b =>
                {
                    b.Property<string>("RelativePath")
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<int>("RecordOrdinal")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("RelativePath", "RecordOrdinal");

                    b.ToTable("ModifierCatalogues", (string)null);
                });

            modelBuilder.Entity("Shuttle.Fhm.Serde.Sqlite.Entities.Name", b =>
                {
                    b.Property<int>("NameId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryWeight")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FlagA")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FlagB")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FlagC")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GroupId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ordinal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .HasColumnType("TEXT");

                    b.HasKey("NameId");

                    b.HasIndex("Ordinal")
                        .IsUnique();

                    b.ToTable("Names", (string)null);
                });

            modelBuilder.Entity("Shuttle.Fhm.Serde.Sqlite.Entities.NameListEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("NameId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NationIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ordinal")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("NameId");

                    b.HasIndex("Kind", "NationIndex", "Ordinal")
                        .IsUnique();

                    b.ToTable("NameListEntries", (string)null);
                });

            modelBuilder.Entity("Shuttle.Fhm.Serde.Sqlite.Entities.NameScalar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Ordinal")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Value")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Kind", "Ordinal")
                        .IsUnique();

                    b.ToTable("NameScalars", (string)null);
                });

            modelBuilder.Entity("Shuttle.Fhm.Serde.Sqlite.Entities.Personnel", b =>
                {
                    b.Property<int>("PersonnelId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BasedInLocationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BirthCityId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BirthDay")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BirthMonth")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BirthYear")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CoachingDefense")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CoachingForwards")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CoachingGoalies")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CoachingProspects")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ContractLength")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DefensiveSkills")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Discipline")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EvaluateAbilities")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EvaluatePotential")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FirstNameNameId")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("GoalieHandlingTendency")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IngameTactics")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("InnovationTendency")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Job")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("LineMatchingTendency")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("LoyaltyTendency")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Motivation")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NationalityId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Negotiating")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("NicknameNameId")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("OffensivePreference")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OffensiveSkills")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("PhysicalPreference")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PhysicalTraining")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PlayerManagement")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Reputation")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Retired")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Salary")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SelfPreservation")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("SerializedRecord")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<int>("SurnameNameId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Tactics")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TeamRecordOrdinal")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TrainerSkill")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("VeteranPreference")
                        .HasColumnType("INTEGER");

                    b.HasKey("PersonnelId");

                    b.HasIndex("FirstNameNameId");

                    b.HasIndex("NicknameNameId");

                    b.HasIndex("SurnameNameId");

                    b.HasIndex("TeamRecordOrdinal");

                    b.ToTable("Personnel", null, t =>
                        {
                            t.HasCheckConstraint("CK_Personnel_BasedInLocationId", "BasedInLocationId BETWEEN 0 AND 65535");

                            t.HasCheckConstraint("CK_Personnel_CoachingDefense", "CoachingDefense BETWEEN 0 AND 20");

                            t.HasCheckConstraint("CK_Personnel_CoachingForwards", "CoachingForwards BETWEEN 0 AND 20");

                            t.HasCheckConstraint("CK_Personnel_CoachingGoalies", "CoachingGoalies BETWEEN 0 AND 20");

                            t.HasCheckConstraint("CK_Personnel_CoachingProspects", "CoachingProspects BETWEEN 0 AND 20");

                            t.HasCheckConstraint("CK_Personnel_ContractLength", "ContractLength IS NULL OR ContractLength BETWEEN 1 AND 255");

                            t.HasCheckConstraint("CK_Personnel_DefensiveSkills", "DefensiveSkills BETWEEN 0 AND 20");

                            t.HasCheckConstraint("CK_Personnel_Discipline", "Discipline BETWEEN 0 AND 20");

                            t.HasCheckConstraint("CK_Personnel_EvaluateAbilities", "EvaluateAbilities BETWEEN 0 AND 20");

                            t.HasCheckConstraint("CK_Personnel_EvaluatePotential", "EvaluatePotential BETWEEN 0 AND 20");

                            t.HasCheckConstraint("CK_Personnel_IngameTactics", "IngameTactics BETWEEN 0 AND 20");

                            t.HasCheckConstraint("CK_Personnel_Motivation", "Motivation BETWEEN 0 AND 20");

                            t.HasCheckConstraint("CK_Personnel_NationalityId", "NationalityId BETWEEN 0 AND 65535");

                            t.HasCheckConstraint("CK_Personnel_Negotiating", "Negotiating BETWEEN 0 AND 20");

                            t.HasCheckConstraint("CK_Personnel_OffensiveSkills", "OffensiveSkills BETWEEN 0 AND 20");

                            t.HasCheckConstraint("CK_Personnel_PhysicalTraining", "PhysicalTraining BETWEEN 0 AND 20");

                            t.HasCheckConstraint("CK_Personnel_PlayerManagement", "PlayerManagement BETWEEN 0 AND 20");

                            t.HasCheckConstraint("CK_Personnel_Reputation", "Reputation BETWEEN 0 AND 100");

                            t.HasCheckConstraint("CK_Personnel_SelfPreservation", "SelfPreservation BETWEEN 0 AND 20");

                            t.HasCheckConstraint("CK_Personnel_Tactics", "Tactics BETWEEN 0 AND 20");

                            t.HasCheckConstraint("CK_Personnel_TrainerSkill", "TrainerSkill BETWEEN 0 AND 20");
                        });
                });

            modelBuilder.Entity("Shuttle.Fhm.Serde.Sqlite.Entities.Player", b =>
                {
                    b.Property<int>("InternalId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CommonNameId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExternalId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FirstNameId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FranchiseId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PrimaryContractRole")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RecordOrdinal")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("SerializedRecord")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<int>("SupplementaryContractRole")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SurnameId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TeamRecordOrdinal")
                        .HasColumnType("INTEGER");

                    b.HasKey("InternalId");

                    b.HasIndex("CommonNameId");

                    b.HasIndex("FirstNameId");

                    b.HasIndex("RecordOrdinal")
                        .IsUnique();

                    b.HasIndex("SurnameId");

                    b.HasIndex("TeamRecordOrdinal");

                    b.ToTable("Players", (string)null);
                });

            modelBuilder.Entity("Shuttle.Fhm.Serde.Sqlite.Entities.PlayerAttributes", b =>
                {
                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Acceleration")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Adaptability")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Aggression")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Agility")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Aging")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ambition")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Balance")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BigGames")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Bravery")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Checking")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Coachability")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Consistency")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Controversy")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DefensiveRead")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Determination")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DevelopmentRate")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Faceoffs")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Fighting")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GettingOpen")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GoalieBlocker")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GoalieGlove")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GoalieLowShots")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GoaliePassing")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GoaliePokeCheck")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GoaliePositioning")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GoaliePuckhandling")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GoalieRebound")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GoalieRecovery")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GoalieStamina")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Greed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HandleCritics")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HandleFailure")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HandleSuccess")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Hitting")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Intelligence")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Leadership")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Loyalty")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MentalToughness")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mood")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OffensiveRead")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PassShootTendency")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Passing")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Positioning")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Professionalism")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Puckhandling")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Reflexes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Screening")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ShootingAccuracy")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ShootingRange")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ShotBlocking")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Skating")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Speed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Sportsmanship")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Stamina")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Stickchecking")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Strength")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeamPlayer")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Temperament")
                        .HasColumnType("INTEGER");

                    b.HasKey("PlayerId");

                    b.ToTable("PlayerAttributes", (string)null);
                });

            modelBuilder.Entity("Shuttle.Fhm.Serde.Sqlite.Entities.PlayerContract", b =>
                {
                    b.Property<int>("PlayerInternalId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ContractOrdinal")
                        .HasColumnType("INTEGER");

                    b.HasKey("PlayerInternalId", "ContractOrdinal");

                    b.ToTable("PlayerContracts", (string)null);
                });

            modelBuilder.Entity("Shuttle.Fhm.Serde.Sqlite.Entities.PlayerContractYear", b =>
                {
                    b.Property<int>("PlayerInternalId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ContractOrdinal")
                        .HasColumnType("INTEGER");

                    b.Property<int>("YearNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MajorLeagueSalary")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MinorLeagueSalary")
                        .HasColumnType("INTEGER");

                    b.HasKey("PlayerInternalId", "ContractOrdinal", "YearNumber");

                    b.ToTable("PlayerContractYears", null, t =>
                        {
                            t.HasCheckConstraint("CK_PlayerContractYears_MajorLeagueSalary", "MajorLeagueSalary IS NULL OR MajorLeagueSalary >= 0");

                            t.HasCheckConstraint("CK_PlayerContractYears_MinorLeagueSalary", "MinorLeagueSalary IS NULL OR MinorLeagueSalary >= 0");

                            t.HasCheckConstraint("CK_PlayerContractYears_YearNumber", "YearNumber BETWEEN 1 AND 14");
                        });
                });

            modelBuilder.Entity("Shuttle.Fhm.Serde.Sqlite.Entities.PlayerRoleAssignment", b =>
                {
                    b.Property<int>("PlayerInternalId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Slot")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PlayerInternalId", "Slot");

                    b.HasIndex("RoleId");

                    b.ToTable("PlayerTacticalRoleAssignments", (string)null);
                });

            modelBuilder.Entity("Shuttle.Fhm.Serde.Sqlite.Entities.PlayerRoleCatalogue", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VersionTag")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("TacticalRoleCatalogue", (string)null);
                });

            modelBuilder.Entity("Shuttle.Fhm.Serde.Sqlite.Entities.PlayerRoleDefinition", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AppliesToDefencemen")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AppliesToForwards")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AppliesToGoalies")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("PositionCategory")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RecordOrdinal")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoleFlags")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ShortName")
                        .HasColumnType("TEXT");

                    b.Property<int>("TuningValueA")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TuningValueB")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TuningValueC")
                        .HasColumnType("INTEGER");

                    b.HasKey("RoleId");

                    b.HasIndex("RecordOrdinal")
                        .IsUnique();

                    b.ToTable("TacticalRoles", null, t =>
                        {
                            t.HasCheckConstraint("CK_PlayerRoles_AppliesToDefencemen", "AppliesToDefencemen BETWEEN 0 AND 255");

                            t.HasCheckConstraint("CK_PlayerRoles_AppliesToForwards", "AppliesToForwards BETWEEN 0 AND 255");

                            t.HasCheckConstraint("CK_PlayerRoles_AppliesToGoalies", "AppliesToGoalies BETWEEN 0 AND 255");

                            t.HasCheckConstraint("CK_PlayerRoles_PositionCategory", "PositionCategory BETWEEN 0 AND 65535");

                            t.HasCheckConstraint("CK_PlayerRoles_RoleFlags", "RoleFlags BETWEEN 0 AND 255");

                            t.HasCheckConstraint("CK_PlayerRoles_TuningValueA", "TuningValueA BETWEEN 0 AND 65535");

                            t.HasCheckConstraint("CK_PlayerRoles_TuningValueB", "TuningValueB BETWEEN 0 AND 65535");

                            t.HasCheckConstraint("CK_PlayerRoles_TuningValueC", "TuningValueC BETWEEN 0 AND 65535");
                        });
                });

            modelBuilder.Entity("Shuttle.Fhm.Serde.Sqlite.Entities.PlayerRoleIndexEntry", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("List")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ordinal")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Value")
                        .HasColumnType("INTEGER");

                    b.HasKey("RoleId", "List", "Ordinal");

                    b.ToTable("TacticalRoleIndexEntries", null, t =>
                        {
                            t.HasCheckConstraint("CK_PlayerRoleIndexEntries_Value", "Value BETWEEN 0 AND 255");
                        });
                });

            modelBuilder.Entity("Shuttle.Fhm.Serde.Sqlite.Entities.PlayerRoleTendencyValue", b =>
                {
                    b.Property<int>("PlayerInternalId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Slot")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tendency")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UseOverride")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Value")
                        .HasColumnType("INTEGER");

                    b.HasKey("PlayerInternalId", "Slot", "Tendency");

                    b.ToTable("PlayerTacticalRoleTendencyValues", null, t =>
                        {
                            t.HasCheckConstraint("CK_PlayerRoleTendencyValues_UseOverride", "UseOverride BETWEEN 0 AND 255");

                            t.HasCheckConstraint("CK_PlayerRoleTendencyValues_Value", "Value BETWEEN 0 AND 65535");
                        });
                });

            modelBuilder.Entity("Shuttle.Fhm.Serde.Sqlite.Entities.PlayerRoleWeight", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Group")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ordinal")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Value")
                        .HasColumnType("INTEGER");

                    b.HasKey("RoleId", "Group", "Ordinal");

                    b.ToTable("TacticalRoleWeights", (string)null);
                });

            modelBuilder.Entity("Shuttle.Fhm.Serde.Sqlite.Entities.SaveFile", b =>
                {
                    b.Property<string>("RelativePath")
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.HasKey("RelativePath");

                    b.HasIndex("RelativePath")
                        .IsUnique();

                    b.ToTable("SaveFiles", (string)null);
                });

            modelBuilder.Entity("Shuttle.Fhm.Serde.Sqlite.Entities.SaveFileChunk", b =>
                {
                    b.Property<string>("RelativePath")
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<int>("Ordinal")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("RelativePath", "Ordinal");

                    b.ToTable("SaveFileChunks", (string)null);
                });

            modelBuilder.Entity("Shuttle.Fhm.Serde.Sqlite.Entities.SaveManifest", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SourceFileCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceFormatVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SaveManifest", (string)null);
                });

            modelBuilder.Entity("Shuttle.Fhm.Serde.Sqlite.Entities.SetPlay", b =>
                {
                    b.Property<string>("RelativePath")
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<bool>("IsExtraRecord")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RecordOrdinal")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("RelativePath", "IsExtraRecord", "RecordOrdinal");

                    b.ToTable("SetPlays", (string)null);
                });

            modelBuilder.Entity("Shuttle.Fhm.Serde.Sqlite.Entities.StoredLine", b =>
                {
                    b.Property<int>("LineOrdinal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TeamRecordOrdinal")
                        .HasColumnType("INTEGER");

                    b.HasKey("LineOrdinal");

                    b.HasIndex("TeamRecordOrdinal");

                    b.ToTable("StoredLines", (string)null);
                });

            modelBuilder.Entity("Shuttle.Fhm.Serde.Sqlite.Entities.StoredLineSlot", b =>
                {
                    b.Property<int>("LineOrdinal")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GroupOrdinal")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SlotOrdinal")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PlayerInternalId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UnitLock")
                        .HasColumnType("INTEGER");

                    b.HasKey("LineOrdinal", "GroupOrdinal", "SlotOrdinal");

                    b.HasIndex("PlayerInternalId");

                    b.ToTable("StoredLineSlots", (string)null);
                });

            modelBuilder.Entity("Shuttle.Fhm.Serde.Sqlite.Entities.TacticFile", b =>
                {
                    b.Property<string>("RelativePath")
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RecordCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("RelativePath");

                    b.ToTable("TacticFiles", (string)null);
                });

            modelBuilder.Entity("Shuttle.Fhm.Serde.Sqlite.Entities.TacticSystem", b =>
                {
                    b.Property<int>("RecordOrdinal")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GlobalId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("RatingA")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RatingB")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ZoneGroupRaw")
                        .HasColumnType("INTEGER");

                    b.HasKey("RecordOrdinal");

                    b.ToTable("TacticSystems", (string)null);
                });

            modelBuilder.Entity("Shuttle.Fhm.Serde.Sqlite.Entities.TacticTemplate", b =>
                {
                    b.Property<int>("RecordOrdinal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("InternalKey")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("SettingsBlob")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<int>("TemplateIndex")
                        .HasColumnType("INTEGER");

                    b.HasKey("RecordOrdinal");

                    b.ToTable("TacticTemplates", (string)null);
                });

            modelBuilder.Entity("Shuttle.Fhm.Serde.Sqlite.Entities.Tactics", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("RecordsOpaque")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<int>("TacticCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Tactics", (string)null);
                });

            modelBuilder.Entity("Shuttle.Fhm.Serde.Sqlite.Entities.Team", b =>
                {
                    b.Property<int>("RecordOrdinal")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AffiliateParentRecordOrdinal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.Property<int>("ConferenceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DivisionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FanLoyalty")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Finance1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Finance2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Finance3")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Finance4")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Flag1")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InternalCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("InternalCode2")
                        .HasColumnType("TEXT");

                    b.Property<int>("LeagueId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LocationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MarketSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nickname")
                        .HasColumnType("TEXT");

                    b.Property<int>("NicknamePlacement")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RecordIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SecondaryAffiliateParentRecordOrdinal")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeamId")
                        .HasColumnType("INTEGER");

                    b.HasKey("RecordOrdinal");

                    b.HasIndex("AffiliateParentRecordOrdinal");

                    b.HasIndex("SecondaryAffiliateParentRecordOrdinal");

                    b.ToTable("Teams", (string)null);
                });

            modelBuilder.Entity("Shuttle.Fhm.Serde.Sqlite.Entities.TeamActiveLineSlot", b =>
                {
                    b.Property<int>("TeamRecordOrdinal")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Group")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SlotOrdinal")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PlayerInternalId")
                        .HasColumnType("INTEGER");

                    b.HasKey("TeamRecordOrdinal", "Group", "SlotOrdinal");

                    b.HasIndex("PlayerInternalId");

                    b.ToTable("TeamActiveLineSlots", null, t =>
                        {
                            t.HasCheckConstraint("CK_TeamActiveLineSlots_Group", "\"Group\" >= 0 AND \"Group\" <= 12");

                            t.HasCheckConstraint("CK_TeamActiveLineSlots_SlotOrdinal", "SlotOrdinal >= 0");
                        });
                });

            modelBuilder.Entity("Shuttle.Fhm.Serde.Sqlite.Entities.TeamTactic", b =>
                {
                    b.Property<int>("TeamRecordOrdinal")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("SerializedSettings")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("TeamRecordOrdinal");

                    b.ToTable("TeamTactics", (string)null);
                });

            modelBuilder.Entity("Shuttle.Fhm.Serde.Sqlite.Entities.ByteGameSetting", b =>
                {
                    b.HasBaseType("Shuttle.Fhm.Serde.Sqlite.Entities.GameSetting");

                    b.Property<byte>("Value")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ByteValue");

                    b.HasDiscriminator().HasValue("Byte");
                });

            modelBuilder.Entity("Shuttle.Fhm.Serde.Sqlite.Entities.DoubleGameSetting", b =>
                {
                    b.HasBaseType("Shuttle.Fhm.Serde.Sqlite.Entities.GameSetting");

                    b.Property<double>("Value")
                        .HasColumnType("REAL")
                        .HasColumnName("DoubleValue");

                    b.HasDiscriminator().HasValue("Double");
                });

            modelBuilder.Entity("Shuttle.Fhm.Serde.Sqlite.Entities.Int32GameSetting", b =>
                {
                    b.HasBaseType("Shuttle.Fhm.Serde.Sqlite.Entities.GameSetting");

                    b.Property<int>("Value")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Int32Value");

                    b.HasDiscriminator().HasValue("Int32");
                });

            modelBuilder.Entity("Shuttle.Fhm.Serde.Sqlite.Entities.QStringGameSetting", b =>
                {
                    b.HasBaseType("Shuttle.Fhm.Serde.Sqlite.Entities.GameSetting");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT")
                        .HasColumnName("StringValue");

                    b.HasDiscriminator().HasValue("QString");
                });

            modelBuilder.Entity("Shuttle.Fhm.Serde.Sqlite.Entities.UInt16GameSetting", b =>
                {
                    b.HasBaseType("Shuttle.Fhm.Serde.Sqlite.Entities.GameSetting");

                    b.Property<ushort>("Value")
                        .HasColumnType("INTEGER")
                        .HasColumnName("UInt16Value");

                    b.HasDiscriminator().HasValue("UInt16");
                });

            modelBuilder.Entity("Shuttle.Fhm.Serde.Sqlite.Entities.NameListEntry", b =>
                {
                    b.HasOne("Shuttle.Fhm.Serde.Sqlite.Entities.Name", "Name")
                        .WithMany()
                        .HasForeignKey("NameId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Name");
                });

            modelBuilder.Entity("Shuttle.Fhm.Serde.Sqlite.Entities.Personnel", b =>
                {
                    b.HasOne("Shuttle.Fhm.Serde.Sqlite.Entities.Name", "FirstName")
                        .WithMany()
                        .HasForeignKey("FirstNameNameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Shuttle.Fhm.Serde.Sqlite.Entities.Name", "Nickname")
                        .WithMany()
                        .HasForeignKey("NicknameNameId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Shuttle.Fhm.Serde.Sqlite.Entities.Name", "Surname")
                        .WithMany()
                        .HasForeignKey("SurnameNameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Shuttle.Fhm.Serde.Sqlite.Entities.Team", "Team")
                        .WithMany("Staff")
                        .HasForeignKey("TeamRecordOrdinal")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("FirstName");

                    b.Navigation("Nickname");

                    b.Navigation("Surname");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Shuttle.Fhm.Serde.Sqlite.Entities.Player", b =>
                {
                    b.HasOne("Shuttle.Fhm.Serde.Sqlite.Entities.Name", "CommonName")
                        .WithMany()
                        .HasForeignKey("CommonNameId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Shuttle.Fhm.Serde.Sqlite.Entities.Name", "FirstName")
                        .WithMany()
                        .HasForeignKey("FirstNameId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Shuttle.Fhm.Serde.Sqlite.Entities.Name", "Surname")
                        .WithMany()
                        .HasForeignKey("SurnameId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Shuttle.Fhm.Serde.Sqlite.Entities.Team", "Team")
                        .WithMany("Players")
                        .HasForeignKey("TeamRecordOrdinal")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.OwnsOne("Shuttle.Fhm.Serde.Sqlite.Entities.PlayerPositionAffinity", "PositionAffinity", b1 =>
                        {
                            b1.Property<int>("PlayerInternalId")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Center")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Center");

                            b1.Property<int>("Goalie")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Goalie");

                            b1.Property<int>("LeftDefense")
                                .HasColumnType("INTEGER")
                                .HasColumnName("LeftDefense");

                            b1.Property<int>("LeftWing")
                                .HasColumnType("INTEGER")
                                .HasColumnName("LeftWing");

                            b1.Property<int>("RightDefense")
                                .HasColumnType("INTEGER")
                                .HasColumnName("RightDefense");

                            b1.Property<int>("RightWing")
                                .HasColumnType("INTEGER")
                                .HasColumnName("RightWing");

                            b1.HasKey("PlayerInternalId");

                            b1.ToTable("Players");

                            b1.WithOwner()
                                .HasForeignKey("PlayerInternalId");
                        });

                    b.Navigation("CommonName");

                    b.Navigation("FirstName");

                    b.Navigation("PositionAffinity")
                        .IsRequired();

                    b.Navigation("Surname");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Shuttle.Fhm.Serde.Sqlite.Entities.PlayerAttributes", b =>
                {
                    b.HasOne("Shuttle.Fhm.Serde.Sqlite.Entities.Player", "Player")
                        .WithOne("Attributes")
                        .HasForeignKey("Shuttle.Fhm.Serde.Sqlite.Entities.PlayerAttributes", "PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Shuttle.Fhm.Serde.Sqlite.Entities.PlayerContract", b =>
                {
                    b.HasOne("Shuttle.Fhm.Serde.Sqlite.Entities.Player", "Player")
                        .WithMany("Contracts")
                        .HasForeignKey("PlayerInternalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Shuttle.Fhm.Serde.Sqlite.Entities.PlayerContractYear", b =>
                {
                    b.HasOne("Shuttle.Fhm.Serde.Sqlite.Entities.PlayerContract", "Contract")
                        .WithMany("Years")
                        .HasForeignKey("PlayerInternalId", "ContractOrdinal")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contract");
                });

            modelBuilder.Entity("Shuttle.Fhm.Serde.Sqlite.Entities.PlayerRoleAssignment", b =>
                {
                    b.HasOne("Shuttle.Fhm.Serde.Sqlite.Entities.Player", "Player")
                        .WithMany("TacticalRoleAssignments")
                        .HasForeignKey("PlayerInternalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shuttle.Fhm.Serde.Sqlite.Entities.PlayerRoleDefinition", "Role")
                        .WithMany("PlayerAssignments")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Shuttle.Fhm.Serde.Sqlite.Entities.PlayerRoleIndexEntry", b =>
                {
                    b.HasOne("Shuttle.Fhm.Serde.Sqlite.Entities.PlayerRoleDefinition", "Role")
                        .WithMany("IndexEntries")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Shuttle.Fhm.Serde.Sqlite.Entities.PlayerRoleTendencyValue", b =>
                {
                    b.HasOne("Shuttle.Fhm.Serde.Sqlite.Entities.PlayerRoleAssignment", "Assignment")
                        .WithMany("Tendencies")
                        .HasForeignKey("PlayerInternalId", "Slot")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assignment");
                });

            modelBuilder.Entity("Shuttle.Fhm.Serde.Sqlite.Entities.PlayerRoleWeight", b =>
                {
                    b.HasOne("Shuttle.Fhm.Serde.Sqlite.Entities.PlayerRoleDefinition", "Role")
                        .WithMany("Weights")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Shuttle.Fhm.Serde.Sqlite.Entities.SaveFileChunk", b =>
                {
                    b.HasOne("Shuttle.Fhm.Serde.Sqlite.Entities.SaveFile", null)
                        .WithMany()
                        .HasForeignKey("RelativePath")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Shuttle.Fhm.Serde.Sqlite.Entities.StoredLine", b =>
                {
                    b.HasOne("Shuttle.Fhm.Serde.Sqlite.Entities.Team", "Team")
                        .WithMany("StoredLines")
                        .HasForeignKey("TeamRecordOrdinal")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Shuttle.Fhm.Serde.Sqlite.Entities.StoredLineSlot", b =>
                {
                    b.HasOne("Shuttle.Fhm.Serde.Sqlite.Entities.StoredLine", "StoredLine")
                        .WithMany("Slots")
                        .HasForeignKey("LineOrdinal")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shuttle.Fhm.Serde.Sqlite.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerInternalId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Player");

                    b.Navigation("StoredLine");
                });

            modelBuilder.Entity("Shuttle.Fhm.Serde.Sqlite.Entities.Team", b =>
                {
                    b.HasOne("Shuttle.Fhm.Serde.Sqlite.Entities.Team", "AffiliateParent")
                        .WithMany()
                        .HasForeignKey("AffiliateParentRecordOrdinal")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Shuttle.Fhm.Serde.Sqlite.Entities.Team", "SecondaryAffiliateParent")
                        .WithMany()
                        .HasForeignKey("SecondaryAffiliateParentRecordOrdinal")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AffiliateParent");

                    b.Navigation("SecondaryAffiliateParent");
                });

            modelBuilder.Entity("Shuttle.Fhm.Serde.Sqlite.Entities.TeamActiveLineSlot", b =>
                {
                    b.HasOne("Shuttle.Fhm.Serde.Sqlite.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerInternalId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Shuttle.Fhm.Serde.Sqlite.Entities.Team", "Team")
                        .WithMany("ActiveLineSlots")
                        .HasForeignKey("TeamRecordOrdinal")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Shuttle.Fhm.Serde.Sqlite.Entities.TeamTactic", b =>
                {
                    b.HasOne("Shuttle.Fhm.Serde.Sqlite.Entities.Team", "Team")
                        .WithOne("Tactics")
                        .HasForeignKey("Shuttle.Fhm.Serde.Sqlite.Entities.TeamTactic", "TeamRecordOrdinal")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Shuttle.Fhm.Serde.Sqlite.Entities.Player", b =>
                {
                    b.Navigation("Attributes")
                        .IsRequired();

                    b.Navigation("Contracts");

                    b.Navigation("TacticalRoleAssignments");
                });

            modelBuilder.Entity("Shuttle.Fhm.Serde.Sqlite.Entities.PlayerContract", b =>
                {
                    b.Navigation("Years");
                });

            modelBuilder.Entity("Shuttle.Fhm.Serde.Sqlite.Entities.PlayerRoleAssignment", b =>
                {
                    b.Navigation("Tendencies");
                });

            modelBuilder.Entity("Shuttle.Fhm.Serde.Sqlite.Entities.PlayerRoleDefinition", b =>
                {
                    b.Navigation("IndexEntries");

                    b.Navigation("PlayerAssignments");

                    b.Navigation("Weights");
                });

            modelBuilder.Entity("Shuttle.Fhm.Serde.Sqlite.Entities.StoredLine", b =>
                {
                    b.Navigation("Slots");
                });

            modelBuilder.Entity("Shuttle.Fhm.Serde.Sqlite.Entities.Team", b =>
                {
                    b.Navigation("ActiveLineSlots");

                    b.Navigation("Players");

                    b.Navigation("Staff");

                    b.Navigation("StoredLines");

                    b.Navigation("Tactics")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
