// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shuttle.Fhm.Serde.Sqlite;

#nullable disable

namespace Shuttle.Fhm.Serde.Sqlite.Migrations
{
    [DbContext(typeof(FhmSaveSqliteContext))]
    [Migration("20260820004518_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("Shuttle.Fhm.Serde.Sqlite.GameSettingProjection", b =>
                {
                    b.Property<int>("SettingOrdinal")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("IntegerValue")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("RealValue")
                        .HasColumnType("REAL");

                    b.Property<string>("TextValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("ValueKind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SettingOrdinal");

                    b.ToTable("GameSettings", (string)null);
                });

            modelBuilder.Entity("Shuttle.Fhm.Serde.Sqlite.ModifierCatalogueProjection", b =>
                {
                    b.Property<string>("RelativePath")
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<int>("RecordOrdinal")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("RelativePath", "RecordOrdinal");

                    b.ToTable("ModifierCatalogues", (string)null);
                });

            modelBuilder.Entity("Shuttle.Fhm.Serde.Sqlite.NameProjection", b =>
                {
                    b.Property<string>("CollectionKind")
                        .HasColumnType("TEXT");

                    b.Property<int>("NationIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ordinal")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryWeight")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FlagA")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FlagB")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FlagC")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GroupId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IntegerValue")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NameId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .HasColumnType("TEXT");

                    b.HasKey("CollectionKind", "NationIndex", "Ordinal");

                    b.ToTable("Names", (string)null);
                });

            modelBuilder.Entity("Shuttle.Fhm.Serde.Sqlite.PlayerAttributesProjection", b =>
                {
                    b.Property<int>("RecordOrdinal")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Acceleration")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Adaptability")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Aggression")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Agility")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Aging")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ambition")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Balance")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BigGames")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Bravery")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Checking")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Coachability")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Consistency")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Controversy")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DefensiveRead")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Determination")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DevRate")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Faceoffs")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Fighting")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GettingOpen")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GoalieBlocker")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GoalieGlove")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GoalieLowShots")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GoaliePassing")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GoaliePokecheck")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GoaliePositioning")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GoaliePuckhandling")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GoalieRebound")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GoalieRecovery")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GoalieReflexes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GoalieSkating")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GoalieStamina")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Greed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HandleCritics")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HandleFailure")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HandleSuccess")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Hitting")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Intelligence")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Leadership")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Loyalty")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MentalToughness")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mood")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OffensiveRead")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PassShootTendency")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Passing")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Positioning")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Professionalism")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PuckHandling")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Screening")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ShootingAccuracy")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ShootingRange")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ShotBlocking")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Speed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Sportsmanship")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Stamina")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Stickchecking")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Strength")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Teamplayer")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Temperament")
                        .HasColumnType("INTEGER");

                    b.HasKey("RecordOrdinal");

                    b.ToTable("PlayerAttributes", (string)null);
                });

            modelBuilder.Entity("Shuttle.Fhm.Serde.Sqlite.PlayerProjection", b =>
                {
                    b.Property<int>("RecordOrdinal")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BirthDay")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BirthMonth")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BirthYear")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Centre")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CommonNameId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExternalId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FirstNameId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FranchiseId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Goalie")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InternalId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LeftDefenceman")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LeftWing")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RightDefenceman")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RightWing")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("SerializedRecord")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<int>("SurnameId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeamId")
                        .HasColumnType("INTEGER");

                    b.HasKey("RecordOrdinal");

                    b.ToTable("Players", (string)null);
                });

            modelBuilder.Entity("Shuttle.Fhm.Serde.Sqlite.SaveFile", b =>
                {
                    b.Property<string>("RelativePath")
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.HasKey("RelativePath");

                    b.HasIndex("RelativePath")
                        .IsUnique();

                    b.ToTable("SaveFiles", (string)null);
                });

            modelBuilder.Entity("Shuttle.Fhm.Serde.Sqlite.SaveManifest", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SourceFileCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceFormatVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SaveManifest", (string)null);
                });

            modelBuilder.Entity("Shuttle.Fhm.Serde.Sqlite.SetPlayProjection", b =>
                {
                    b.Property<string>("RelativePath")
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<bool>("IsExtraRecord")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RecordOrdinal")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("RelativePath", "IsExtraRecord", "RecordOrdinal");

                    b.ToTable("SetPlays", (string)null);
                });

            modelBuilder.Entity("Shuttle.Fhm.Serde.Sqlite.StoredLineProjection", b =>
                {
                    b.Property<int>("LineOrdinal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("LineOrdinal");

                    b.ToTable("StoredLines", (string)null);
                });

            modelBuilder.Entity("Shuttle.Fhm.Serde.Sqlite.StoredLineSlotProjection", b =>
                {
                    b.Property<int>("LineOrdinal")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GroupOrdinal")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SlotOrdinal")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PlayerInternalId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UnitLock")
                        .HasColumnType("INTEGER");

                    b.HasKey("LineOrdinal", "GroupOrdinal", "SlotOrdinal");

                    b.ToTable("StoredLineSlots", (string)null);
                });

            modelBuilder.Entity("Shuttle.Fhm.Serde.Sqlite.TacticFileProjection", b =>
                {
                    b.Property<string>("RelativePath")
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RecordCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("RelativePath");

                    b.ToTable("TacticFiles", (string)null);
                });

            modelBuilder.Entity("Shuttle.Fhm.Serde.Sqlite.TacticSystemProjection", b =>
                {
                    b.Property<int>("RecordOrdinal")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GlobalId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("RatingA")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RatingB")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ZoneGroupRaw")
                        .HasColumnType("INTEGER");

                    b.HasKey("RecordOrdinal");

                    b.ToTable("TacticSystems", (string)null);
                });

            modelBuilder.Entity("Shuttle.Fhm.Serde.Sqlite.TacticTemplateProjection", b =>
                {
                    b.Property<int>("RecordOrdinal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("InternalKey")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("SettingsBlob")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<int>("TemplateIndex")
                        .HasColumnType("INTEGER");

                    b.HasKey("RecordOrdinal");

                    b.ToTable("TacticTemplates", (string)null);
                });

            modelBuilder.Entity("Shuttle.Fhm.Serde.Sqlite.TacticsProjection", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("RecordsOpaque")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<int>("TacticCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Tactics", (string)null);
                });

            modelBuilder.Entity("Shuttle.Fhm.Serde.Sqlite.TeamProjection", b =>
                {
                    b.Property<int>("RecordOrdinal")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AffiliateParentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AffiliateParentId2")
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.Property<int>("ConferenceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DivisionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FanLoyalty")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Finance1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Finance2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Finance3")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Finance4")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Flag1")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InternalCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("InternalCode2")
                        .HasColumnType("TEXT");

                    b.Property<int>("LeagueId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LocationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MarketSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nickname")
                        .HasColumnType("TEXT");

                    b.Property<int>("NicknamePlacement")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RecordIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeamId")
                        .HasColumnType("INTEGER");

                    b.HasKey("RecordOrdinal");

                    b.ToTable("Teams", (string)null);
                });

            modelBuilder.Entity("Shuttle.Fhm.Serde.Sqlite.TeamTacticProjection", b =>
                {
                    b.Property<int>("TeamRecordOrdinal")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("SerializedSettings")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("TeamRecordOrdinal");

                    b.ToTable("TeamTactics", (string)null);
                });

            modelBuilder.Entity("Shuttle.Fhm.Serde.Sqlite.PlayerAttributesProjection", b =>
                {
                    b.HasOne("Shuttle.Fhm.Serde.Sqlite.PlayerProjection", null)
                        .WithOne()
                        .HasForeignKey("Shuttle.Fhm.Serde.Sqlite.PlayerAttributesProjection", "RecordOrdinal")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Shuttle.Fhm.Serde.Sqlite.StoredLineSlotProjection", b =>
                {
                    b.HasOne("Shuttle.Fhm.Serde.Sqlite.StoredLineProjection", null)
                        .WithMany()
                        .HasForeignKey("LineOrdinal")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Shuttle.Fhm.Serde.Sqlite.TeamTacticProjection", b =>
                {
                    b.HasOne("Shuttle.Fhm.Serde.Sqlite.TeamProjection", null)
                        .WithOne()
                        .HasForeignKey("Shuttle.Fhm.Serde.Sqlite.TeamTacticProjection", "TeamRecordOrdinal")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
